apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: samuelcseto/ambulance-ufe
  newName: samuelcseto/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260306.1914 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
