apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - deployment.yaml
    - service.yaml
    - webcomponent-link.yaml
    - webcomponent-content.yaml
    - microfrontend.yaml
    - project.yaml

labels:
    - pairs:
          app.kubernetes.io/component: scs-ambulance-ufe
          app.kubernetes.io/name: scs-ambulance-wl
          wac-fiit.github.io/component: frontend
          wac-fiit.github.io/project: scs-ambulance-wl
