apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
    name: scs-ambulance-ufe-content
spec:
    microFrontend: scs-ambulance-ufe
    element: scs-ambulance-wl-app
    attributes:
        - name: base-path
          value: ./scs-ambulance-wl/
        - name: api-base
          value: http://localhost:5050/api
        - name: ambulance-id
          value: bobulova
    displayRules:
        - allOf:
              - context-name: main-content
              - path: "^(\\.?/)?scs-ambulance-wl(/.*)?$"
